controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api_routes:
    path: /api/{path}
    controller: App\Controller\ApiController::handle
    requirements:
        path: .*

block_other_routes:
    path: /{path}
    controller: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
    requirements:
        path: .*
